apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
spec:
  containers:
    - image: docker_backend
      name: backend-container
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
          name: https
          protocol: TCP
      env:
        - name: DATABASE_URL
          value: "postgresql+psycopg2://test:test@db:5432/test"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"