apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: docker_backend
        name: backend-container
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
            name: http
            protocol: TCP
        env:
          - name: DATABASE_URL
            value: "postgresql+psycopg2://test:test@postgres:5432/test"
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "8000"