apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
spec:
  containers:
    - image: docker_frontend
      name: frontend-container
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: http
          protocol: TCP